#!/usr/bin/env escript
%%! -smp enable debug verbose
main([String]) ->
  try
    net_kernel:start([temp_name, shortnames]),
    node:start(),
    node:connect(foo@bar),
    node:send(String),
    node:stop(),
    io:format("done~n")
  catch
    _:_ ->
      usage()
  end;
main(_) ->
  usage().

usage() ->
  io:format("usage: ~p message~n", [escript:script_name()]),
  halt(1).
  